# Generated by Django 5.1.2 on 2024-11-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(max_length=255),
        ),
    ]
