# Generated by Django 5.1.2 on 2024-11-30 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_currency_alter_payment_status_and_more"),
        ("store", "0006_alter_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.book",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
