# Generated by Django 5.1.4 on 2024-12-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_remove_payment_currency_remove_payment_user_and_more"),
        ("store", "0008_category_book_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="book",
        ),
        migrations.AddField(
            model_name="payment",
            name="books",
            field=models.ManyToManyField(to="store.book"),
        ),
    ]
