# Generated by Django 5.1.4 on 2024-12-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_remove_payment_book_payment_books"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="card_brand",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="card_last4",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("paypal", "PayPal"), ("visa", "Visa")],
                max_length=10,
            ),
        ),
    ]
