# Generated by Django 5.1.2 on 2024-11-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_rating_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.FloatField(),
        ),
    ]
