# Generated by Django 5.1.3 on 2024-12-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favouritelist', '0001_initial'),
        ('store', '0007_remove_order_item_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritelistitem',
            unique_together={('favorite_list', 'book')},
        ),
    ]
