# Generated by Django 5.1.3 on 2024-12-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favouritelist', '0002_alter_favoritelistitem_unique_together'),
        ('store', '0007_remove_order_item_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritelistitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='favoritelistitem',
            constraint=models.UniqueConstraint(fields=('favorite_list', 'book'), name='unique_favorite_list_item'),
        ),
    ]
